library(lmerTest)
library(lme4)
library(vegan)
library(fields)
library(linkcomm)
library(picante)
library(raster)

source('src/misc.R')
source('src/cvCalc.R')
load('../../data/networks/allSpecimens.Rdata')
load('../speciesLevel/saved/specs.Rdata')
